// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrgLb8jbfR_VYrfJU8cxdOdGSbxHlZ3Hg',
    appId: '1:1083369455740:web:ee04b4d1a3612cfe0249f9',
    messagingSenderId: '1083369455740',
    projectId: 'digital-memory-capsule-3ff14',
    authDomain: 'digital-memory-capsule-3ff14.firebaseapp.com',
    storageBucket: 'digital-memory-capsule-3ff14.firebasestorage.app',
    measurementId: 'G-NJGKV9KJPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjF8ESaxVL2kUNB0q0VXshHdwlINZlsmk',
    appId: '1:1083369455740:android:c88a9767eabdcaac0249f9',
    messagingSenderId: '1083369455740',
    projectId: 'digital-memory-capsule-3ff14',
    storageBucket: 'digital-memory-capsule-3ff14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt544JUYog6kalu613cqpmycxSIFzcu3o',
    appId: '1:1083369455740:ios:1f79f42223b5e4c40249f9',
    messagingSenderId: '1083369455740',
    projectId: 'digital-memory-capsule-3ff14',
    storageBucket: 'digital-memory-capsule-3ff14.firebasestorage.app',
    iosBundleId: 'com.example.digitalMemoryCapsule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt544JUYog6kalu613cqpmycxSIFzcu3o',
    appId: '1:1083369455740:ios:1f79f42223b5e4c40249f9',
    messagingSenderId: '1083369455740',
    projectId: 'digital-memory-capsule-3ff14',
    storageBucket: 'digital-memory-capsule-3ff14.firebasestorage.app',
    iosBundleId: 'com.example.digitalMemoryCapsule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrgLb8jbfR_VYrfJU8cxdOdGSbxHlZ3Hg',
    appId: '1:1083369455740:web:ca91ad66293b5a550249f9',
    messagingSenderId: '1083369455740',
    projectId: 'digital-memory-capsule-3ff14',
    authDomain: 'digital-memory-capsule-3ff14.firebaseapp.com',
    storageBucket: 'digital-memory-capsule-3ff14.firebasestorage.app',
    measurementId: 'G-VSY361XMTP',
  );
}
